### ISSUE TITLE
Problems with settings and grub2 Linux VM

### ISSUE THREAD

**Issue by MirLach** [alonsobsd/bhyvemgr#1]
I wanted to try your **bhyvemgr** to run an old Ubuntu 16 VM and I ran into a few problems.

1. General settings: Subnet is not saved after change and always reverts to 10.0.0.0/24
2. General settings: the VM directory cannot be changed, why can't I set for example `/tank3/vol0/vms`?
3. I would like to see the possibility to use `sudo` even with a password.
4. I haven't figured out how to start a VM without UEFI. Is it possible to use Bhyvemgr for a classic `grub2` Linux VM?
5. Add new VM settings: memory cannot be arbitrary number, only incremented by arrows (in 256MB steps) - seems strange to me.
6. Add new VM settings: disk size cannot be arbitrary number, only incremented by arrows (in 10GB steps?) - seems strange to me.
7. Initial dialog on the first run has a typo  (a / and): *Review it a press Save settings button if everything is ok* should be **Review it and press Save settings button if everything is OK** 
8. warning message missing "**be**": *freerdp support will not available. net/freerdp3 is not installed.* should be **freerdp support will not be available. net/freerdp3 is not installed.**

Tested the latest package `bhyvemgr-qt5-1.1.0`  on FreeBSD 13.4 amd64 GENERIC.

**Comment by alonsobsd** [comment]
Hello @MirLach 

1) Subnet only works with dnsmasq option is enable. If dnsmasq is not checked, Subnet value is not saved. I'll change this because it is not almost clear

2) Currently it only supports change zroot value. I'll add it to my TODO list

3) Not this time. bhyvemgr has a basic sudo/doas support because it's not need much changes to work with both. If I implement sudo-with-password it could need caching credentials and it is not supported by security/doas. Otherwise you would need put password lot of times while you use bhyvemgr. 

4) grub2-bhyve is no part of bhyve. It is a external tool to enable run bhyve-vm using grub2. I don't know if actually it is necessary or almost uefi can cover all cases

5) Do you need set other value than 256Mb or multiple of 256Mb? I'll change this control to accept direct input

6) Do you need set other value than 10GB or multiple of 10GB? I think the minimal VM disk size used is 10GB. Anyway I'll change this control to accept direct input too

7) I'll fix it

8) I'll fix it

Thanks!

**Comment by MirLach** [comment]
&nbsp; 4. I understand that support for `grub2-bhyve` is more complicated. It would be great to note it in documentation that UEFI is the only supported boot type.
Regarding 5. and 6. all other GUI I ever tried for different hypervisors allowed arbitrary number as an input. I agree that 10GB increments is sufficient in the most cases but in my particular case I tried to setup test environment according to production environment where 16GB image was used. So in this case I really needed to use 16GB disk image instead of 10 or 20 because I need to test disk / partition resize.

Thank you for your replies. Wish you luck with `bhyvemgr`!

**Comment by alonsobsd** [comment]
Committed some changes ([131403789be7be420efaad7061bdf1f171604ef6](https://github.com/alonsobsd/bhyvemgr/commit/131403789be7be420efaad7061bdf1f171604ef6)). Thanks
